name: Cleanup Old Workflow Runs

on:
  schedule:
    - cron: '0 0 * * *' # 每天午夜执行
  workflow_dispatch: # 允许手动触发

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old workflow runs
        uses: actions/delete-workflow-runs@v1
        with:
          retain_days: 3 # 保留最近 30 天的记录
          keep_minimum_runs: 5 # 至少保留 10 条记录
          token: ${{ secrets.GITHUB_TOKEN }}
